---
- name: Setup Ngnix svc
  hosts: websrvgrp
  gather_facts: no
  tasks:
    - name: Install Ngnix
      apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 86400
      tags:
       - package

    - name: Start and enable Ngnix
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
        - svc

    - name: Disable Nginx default website
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      tags:
        - conf

    - name: Deploy web config file
      temples:
        src: templates/nginxvpro.j2
        dest: /etc/nginx/sites-available/vproapp
    tags:
      - conf

    - name: Enable vproapp website
      file:
        src: /etc/nginx/sites-available/vproapp
        dest: /etc/nginx/sites-enabled/vproapp
        state: link
      nofity:
        - Restart Nginx
      tags:
        - conf

 handlers:
   - name: Restart Nginx
     service:
       name: nginx
       state: restarted


